use_frameworks!

platform :ios, '8.0'

target 'MTHome_Example' do
  pod 'MTHome', :path => '../'
  pod "CTMediator"
  pod 'Category_Home', :git => 'https://github.com/MTModule/Category_Home.git'
  
end
